### ISSUE TITLE
Provide linux arm64 build

### ISSUE THREAD

**Issue by rvanider** [interlynk-io/sbomex#40]
Please consider adding a Linux arm64 release.

**Comment by surendrapathak** [comment]
@rvanider Certainly. Let me get back to you!

**Comment by surendrapathak** [comment]
Hi @rvanider - linux-arm64 is now built with v0.0.10. Let me know if you run into any issues. Thanks.

**Comment by rvanider** [comment]
Thanks @surendrapathak
