### ISSUE TITLE
Cannot Access SBOMEX dataset

### ISSUE THREAD

**Issue by rdorff** [interlynk-io/sbomex#51]
Using sbomex to pull SBOMS from the SBOMDB results in the following error:

Using code from SBOMEX GitHub repository example:

$ sbomex pull --id 23
failed to fetch 403

It's suspected that SBOMEX needs to be updated to reflect a change in the database location

**Comment by surendrapathak** [comment]
Thanks for reporting this. I can confirm this is a problem with the DB right now. Unfortunately, we need to build an update to DB with updated location of the SBOMs and that needs a migration. Let us try to get back to you by Monday. Thanks for trying out this utility.

**Comment by surendrapathak** [comment]
Hi @rdorff Thanks for your patience. The db is re-built and accessible with v0.1.0 of sbomex.
If you remove existing version and re-install v0.1.0 version, this one should be resolved : https://github.com/interlynk-io/sbomex/releases/tag/v0.1.0
